# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ab970672cc5cd15af56d9f167b687a9e423c3e73afc817b523a5a2bd796ec3cf3662d6a288b567e3f8b135eb3a2f1579fa36512dd5c8270c4ac0883eda50b7b

test:
  secret_key_base: a2289793c2d576fbfb310c17590868ab61d38573d22deb6aeb0947df68bae3e512e62bfba1d9fcc0bb5facc0da71a253807e40004c2863b19fc91be2d613e719

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
